name: CI + CD Placeholder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write   # safe default; needed later if you use cloud OIDC deploys

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  deploy-placeholder:
    name: Deploy Placeholder (manual approval)
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://Goldratechcker.com  # optional placeholder link
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run placeholder deploy
        run: |
          echo "=== Running Placeholder Deploy ==="
          mkdir -p deploy_output
          echo "Deployed placeholder at $(date)" > deploy_output/info.txt
          ls -l deploy_output
